apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-tech-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abc-tech
  template:
    metadata:
      labels:
        app: abc-tech
    spec:
      containers:
        - name: abc-tech-container
          image: mdakbarali/abc_tech:latest
          ports:
            - containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: abc-tech-service
spec:
  selector:
    app: abc-tech
  ports:
    - protocol: TCP
      port: 8084          # This is the port exposed by the service
      targetPort: 8084    # This is the port on the container
      nodePort: 32547     # Optional: specify a nodePort if you want a fixed port
  type: NodePort
